[build]
publish = public

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
      max-age=31557600,
      no-cache,
      no-store,
      must-revalidate'''
 

[[plugins]]
  package = "netlify-plugin-gatsby-cache"