name: DEV Publisher
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  publish:
    name: Synchronize with DEV
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Cache Python packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements/pub.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install packages
        run: pip install -r actions/devto/requirements.txt

      - name: Run publisher
        run: python actions/devto/sync.py
        env:
          DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
