name: DEV Publisher
on: [push]
jobs:
  get_articles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ./actions
      env:
        DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
