on: [push]

jobs:
  devto:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: actions/hello-world-javascript-action@v1
      env:
        DEV_API_KEY: ${{ secrets.DEV_API_KEY }}